name: Build iOS IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14   # 当前 GitHub 提供的环境，支持 Xcode 15.x
    steps:
      # 拉取仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 选择 Xcode 版本 (这里是 15.4，对应 iOS 17 SDK)
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      # 自动识别是 .xcworkspace 还是 .xcodeproj
      - name: Detect Xcode Project
        id: detect
        run: |
          if ls *.xcworkspace 1> /dev/null 2>&1; then
            echo "type=workspace" >> $GITHUB_ENV
            echo "file=$(ls *.xcworkspace | head -n 1)" >> $GITHUB_ENV
          elif ls *.xcodeproj 1> /dev/null 2>&1; then
            echo "type=project" >> $GITHUB_ENV
            echo "file=$(ls *.xcodeproj | head -n 1)" >> $GITHUB_ENV
          else
            echo "❌ 没找到 .xcodeproj 或 .xcworkspace"
            exit 1
          fi

      # 编译 .app
      - name: Build .app
        run: |
          if [ "${{ env.type }}" = "workspace" ]; then
            xcodebuild \
              -workspace "${{ env.file }}" \
              -scheme APP \
              -sdk iphoneos \
              -configuration Release \
              clean build \
              CONFIGURATION_BUILD_DIR=$PWD/build/Release-iphoneos
          else
            xcodebuild \
              -project "${{ env.file }}" \
              -scheme APP \
              -sdk iphoneos \
              -configuration Release \
              clean build \
              CONFIGURATION_BUILD_DIR=$PWD/build/Release-iphoneos
          fi

      # 打包成 IPA
      - name: Package IPA
        run: |
          mkdir Payload
          cp -r build/Release-iphoneos/APP.app Payload/
          zip -r APP.ipa Payload
          rm -rf Payload

      # 上传 IPA 到 Artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: APP-ipa
          path: APP.ipa
