name: Build iOS IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 拉取源码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 检测项目和 scheme
      - name: Detect project and scheme
        id: detect
        run: |
          # 找到 .xcworkspace 或 .xcodeproj
          workspace=$(find . -maxdepth 1 -name "*.xcworkspace" | head -n 1)
          project=$(find . -maxdepth 1 -name "*.xcodeproj" | head -n 1)

          if [ -n "$workspace" ]; then
            echo "type=workspace" >> $GITHUB_OUTPUT
            echo "file=$workspace" >> $GITHUB_OUTPUT
          elif [ -n "$project" ]; then
            echo "type=project" >> $GITHUB_OUTPUT
            echo "file=$project" >> $GITHUB_OUTPUT
          else
            echo "❌ 没找到 Xcode 工程文件 (.xcworkspace 或 .xcodeproj)"
            exit 1
          fi

          # 自动获取第一个 Scheme
          if [ -n "$workspace" ]; then
            scheme=$(xcodebuild -list -json -workspace "$workspace" | jq -r '.workspace.schemes[0]')
          else
            scheme=$(xcodebuild -list -json -project "$project" | jq -r '.project.schemes[0]')
          fi

          if [ -z "$scheme" ] || [ "$scheme" = "null" ]; then
            echo "❌ 没有找到 scheme"
            exit 1
          fi

          echo "scheme=$scheme" >> $GITHUB_OUTPUT
          echo "✅ 检测到 Scheme: $scheme"

      # 编译 .app
      - name: Build .app
        run: |
          if [ "${{ steps.detect.outputs.type }}" = "workspace" ]; then
            xcodebuild \
              -workspace "${{ steps.detect.outputs.file }}" \
              -scheme "${{ steps.detect.outputs.scheme }}" \
              -sdk iphoneos \
              -destination 'generic/platform=iOS' \
              -configuration Release \
              clean build \
              CONFIGURATION_BUILD_DIR=$PWD/build/Release-iphoneos
          else
            xcodebuild \
              -project "${{ steps.detect.outputs.file }}" \
              -scheme "${{ steps.detect.outputs.scheme }}" \
              -sdk iphoneos \
              -destination 'generic/platform=iOS' \
              -configuration Release \
              clean build \
              CONFIGURATION_BUILD_DIR=$PWD/build/Release-iphoneos
          fi

      # 打包 .app -> .ipa
      - name: Package IPA
        run: |
          mkdir Payload
          app_path=$(ls build/Release-iphoneos/*.app | head -n 1)
          cp -r "$app_path" Payload/
          zip -r App.ipa Payload
          rm -rf Payload

      # 上传 ipa
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: iOS-App-ipa
          path: App.ipa
